import numpy as np, pandas as pd, json, os
from sklearn.model_selection import StratifiedGroupKFold
from sklearn.metrics import roc_auc_score
import xgboost as xgb
df=pd.read_csv("lh_all.csv"); F=[f'f{i}' for i in range(15)]
X=df[F].values.astype(float); y=df.label.values; g=df.sid.values
NAMES=["acc_x__power_2_12_log","acc_x__spectral_centroid","acc_y__spectral_centroid","gyro_y__mad",
"acc_z__spectral_centroid","gyro_x__frequency_stability","acc_z__peak_prominence","acc_x__ratio_3_7_to_2_12",
"gyro_z__mad","gyro_mag__iqr","acc_x__amplitude_variability","acc_z__spectral_entropy","acc_y__ratio_3_7_to_2_12",
"gyro_y__ratio_3_7_to_2_12","gyro_x__spectral_centroid"]
# final hyperparameters (best from sweep): depth=2, eta=0.05, 400 trees, min_child=5
MAX_DEPTH=2; ETA=0.05; NROUND=400; MIN_CHILD=5
P=dict(max_depth=MAX_DEPTH,eta=ETA,min_child_weight=MIN_CHILD,subsample=0.9,colsample_bytree=0.9,
       objective='binary:logistic',tree_method='exact',eval_metric='auc',base_score=0.5)
def flatten(bst):
    FE=[];TH=[];LE=[];RI=[];RO=[]
    for ds in bst.get_dump(dump_format="json"):
        tree=json.loads(ds); order=[]
        def walk(n):
            order.append(n)
            if "children" in n: walk(n["children"][0]); walk(n["children"][1])
        walk(tree); idx={}; base=len(FE)
        for k,n in enumerate(order): idx[n["nodeid"]]=base+k
        RO.append(idx[tree["nodeid"]])
        for n in order:
            if "leaf" in n: FE.append(-1);TH.append(float(n["leaf"]));LE.append(-1);RI.append(-1)
            else:
                FE.append(int(n["split"][1:])); TH.append(float(n["split_condition"]))
                LE.append(idx[n["yes"]]); RI.append(idx[n["no"]])
    return FE,TH,LE,RI,RO
def pym(F,T,L,R,RO,x):
    s=0.0
    for r in RO:
        i=r
        while F[i]!=-1: i=L[i] if x[F[i]]<T[i] else R[i]
        s+=T[i]
    return s
def train_export(pos,neg,tag):
    m=np.isin(y,[pos,neg]); Xm,ym=X[m],(y[m]==pos).astype(int)
    med=np.nanmedian(Xm,0); Xi=np.where(np.isnan(Xm),med,Xm)
    bst=xgb.train(P,xgb.DMatrix(Xi,label=ym),NROUND)
    Fl=flatten(bst); dm=xgb.DMatrix(Xi); bm=bst.predict(dm,output_margin=True)
    mys=np.array([pym(*Fl,Xi[k]) for k in range(len(Xi))])
    inter=float(np.median(bm-mys))
    prob_b=bst.predict(dm); prob_my=1/(1+np.exp(-(mys+inter)))
    perr=float(np.max(np.abs(prob_b-prob_my)))
    print(f"[{tag}] trees={len(Fl[4])} nodes={len(Fl[0])} prob_err={perr:.2e}")
    return dict(F=Fl[0],T=Fl[1],L=Fl[2],R=Fl[3],RO=Fl[4],inter=inter,med=med.tolist())
E={}
E["HC"]=train_export(1,0,"PD_vs_HC"); E["DD"]=train_export(1,2,"PD_vs_DD")
def carr(name,vals,typ,per=20):
    s=f"static const {typ} {name}[{len(vals)}] = {{\n"
    for i in range(0,len(vals),per):
        ch=vals[i:i+per]
        s+="  "+(",".join(f"{v:.7g}f" for v in ch) if typ=="float" else ",".join(str(int(v)) for v in ch))+",\n"
    return s+"};\n"
H=['// Generated by XGBoost (PADS LiftHold single-task, 15 device-side features). Research screening, not a diagnosis.',
   '// Directly replaces the original pads_v3 logistic regression: input is the 15-dim feature vector computed by runPadsModel() in xiao_tremor_compute.ino.',
   '// HC = PD vs healthy (device main output); DD = PD vs other movement disorders (reference). Returns PD probability (0~1).',
   '#pragma once','#include <math.h>','',f'#define PADS_XGB_LH_NFEAT 15','']
for i,n in enumerate(NAMES): H.append(f'//  {i:2d} {n}')
H.append('')
for tag in ("HC","DD"):
    e=E[tag]; p=f"PADS_LH_{tag}"
    H.append(f'#define {p}_NTREE {len(e["RO"])}'); H.append(f'static const float {p}_INTERCEPT = {e["inter"]:.7g}f;')
    H.append(carr(f"{p}_FEAT",e["F"],"short")); H.append(carr(f"{p}_THR",e["T"],"float"))
    H.append(carr(f"{p}_LEFT",e["L"],"short")); H.append(carr(f"{p}_RIGHT",e["R"],"short"))
    H.append(carr(f"{p}_ROOT",e["RO"],"short")); H.append(carr(f"{p}_MEDIAN",e["med"],"float")); H.append('')
H.append(r'''static inline float pads_xgb_lh_predict(const short* FEAT,const float* THR,const short* LEFT,
    const short* RIGHT,const short* ROOT,int ntree,float inter,const float* median,const float* feat){
  float x[PADS_XGB_LH_NFEAT];
  for(int i=0;i<PADS_XGB_LH_NFEAT;i++){ float v=feat[i]; x[i]=(isnan(v)?median[i]:v); }
  float s=inter;
  for(int t=0;t<ntree;t++){ int i=ROOT[t];
    while(FEAT[i]!=-1) i=(x[FEAT[i]]<THR[i])?LEFT[i]:RIGHT[i];
    s+=THR[i]; }
  return 1.0f/(1.0f+expf(-s));
}
static inline float pads_lh_PD_vs_HC(const float* feat){
  return pads_xgb_lh_predict(PADS_LH_HC_FEAT,PADS_LH_HC_THR,PADS_LH_HC_LEFT,PADS_LH_HC_RIGHT,PADS_LH_HC_ROOT,PADS_LH_HC_NTREE,PADS_LH_HC_INTERCEPT,PADS_LH_HC_MEDIAN,feat);
}
static inline float pads_lh_PD_vs_DD(const float* feat){
  return pads_xgb_lh_predict(PADS_LH_DD_FEAT,PADS_LH_DD_THR,PADS_LH_DD_LEFT,PADS_LH_DD_RIGHT,PADS_LH_DD_ROOT,PADS_LH_DD_NTREE,PADS_LH_DD_INTERCEPT,PADS_LH_DD_MEDIAN,feat);
}
static const char* const PADS_XGB_LH_VERSION = "pads-lifthold-xgb-20260818";''')
open("pads_xgb_lifthold_model.h","w").write("\n".join(H))
print("WROTE pads_xgb_lifthold_model.h bytes=",os.path.getsize("pads_xgb_lifthold_model.h"))
json.dump({k:{kk:vv for kk,vv in v.items() if kk in('inter',)} for k,v in E.items()},open("lh_export_meta.json","w"))
